apps/base/urls.py
from django.urls import path
from . import views

app_name = 'basic'

urlpatterns = [
    path("basiс/", views.AboutUsView.as_view(), name="basic"),
    path('', views.index, name='index')
]

apps/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = "users"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("update_u/<int:pk>/", login_required(views.UserUpdateView.as_view()), name="update_u"),
    path("logout", views.logout_request, name="logout"),
    path("profile/<int:pk>", views.UserDetailView.as_view(), name="profile"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("apps.user.urls")),
    path("about/", include("apps.base.urls")),
    path("", include("apps.base.urls_root")),
]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    avatar = models.ImageField(
        max_length=300,
        upload_to="contacts/contact/avatar/",
        blank=True,
        null=True,
        default=None,
    )

apps/base/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


def index(request):

    return render(request=request,
                  template_name="index.html")


class AboutUsView(TemplateView):

    template_name = "base/basic.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "about_us"

        return context

apps/user/views.py
from pyexpat.errors import messages

from django.shortcuts import redirect
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms


User = get_user_model()


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-input"}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-input"}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-input"}))
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput(attrs={"class": "form-input"}))

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "avatar",
        )


class SignUpView(CreateView):
    form_class = RegisterUserForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("login")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("root:index")


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = "registration/login.html"


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    # return redirect("root:index")


class UserUpdateView(UpdateView):
    model = User

    template_name = "registration/update.html"
    fields = (
        "username",
        "email",
        "avatar",
    )
    success_url = reverse_lazy("root:index")


class UserDetailView(DetailView):
    model = User
    template_name = "profile/profile.html"

apps/templates/_helpers/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>

    {# [connect_bootstrap]-[BEGIN] #}
    <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap]-[END] #}

<link
href = "{% static "styles/index.css" %}"
rel = "stylesheet"
>
<link rel="icon" type="image/svg+xml" href="{% static "favicon/favicon.svg" %}">

</head>
<body>
<div class="container-fluid">
    {% include '_helpers/_header.html' %}

    {% block content %}
        Hello!
    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img class="logo" src="{% static "/logo/logo.svg" %}" alt="site-logo"/>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin panel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "root:index" %}"> Home </a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url "basic:basic" %}"> About Us </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:profile' pk=user.id %}">My profile</a>
                </li>
            {% endif %}

        </ul>
    </nav>
    {% if user.is_authenticated %}

        <li class="last">
            <p> {{ user.username }} |<a href="{% url "logout" %}"> Logout </a></p>
            <div class="col my-element-style">
                <div class="user-avatar">
                    {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="Avatar">
                    {% endif %}
                </div>
            </div>

        </li>



    {% else %}
        <li class="last">
            <a href="{% url "login" %}"> Login </a>| <a href="{% url "users:signup" %}"> Signup users</a>
        </li>
    {% endif %}

</header>

apps/templates/accounts/signup.html
{% extends "_helpers/_base.html" %}
{%  block title %} Sign up{%  endblock  %}
{% load crispy_forms_tags %}

{%  block content %}
    <h3> Sign up</h3>

   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Sign up</button>
   </form>
{% endblock %}

apps/templates/base/basic.html
{% extends "_helpers/_base.html" %}

{%  block title %}
    About Us
{%  endblock  %}

{% block content %}
<h1>Hi:)</h1>
<p>
    This is base django project
</p>
{% endblock content %}

apps/templates/index.html
{% extends "_helpers/_base.html" %}
{%  block title %} Sign up{%  endblock  %}
{% load crispy_forms_tags %}

{%  block content %}

   <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Sign up</button>
   </form>
{% endblock %}

apps/templates/profile/profile.html
{% extends '_helpers/_base.html' %}

{% block content %}

    <h1>Welcome to your profile, {{ object.username }}</h1>
    {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="Avatar" width="150">
    {% endif %}

    {% if object.first_name %}
        <p>First name : {{ object.first_name }}</p>
    {% else %}
        <p>First name: "You can add this info"</p>
    {% endif %}

    {% if object.last_name %}
        <p>Last name : {{ object.last_name }}</p>
    {% else %}
        <p>Last name: "You can add this info"</p>
    {% endif %}

    <p>Email : {{ object.email }}</p>

    <div class="my-elements-controls">
        <a href="{% url 'users:update_u' pk=user.id %}">
            <button class="btn btn-success">
                    Edit account
            </button>
        </a>
    </div>
{% endblock %}